# used only for unit testing
[dependencies]
base = "0.8.1"
cap = "https://github.com/Psychedelic/cap-motoko-library#v1.0.4"
accountid = "https://github.com/aviate-labs/principal.mo#v0.2.6"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#v0.0.7"

[dev-dependencies]
test = "1.0.1"
fuzz = "0.1.0"